spring.application.name=Backend-java

spring.datasource.url=jdbc:postgresql://localhost:5432/CadDados
spring.datasource.username=postgres
spring.datasource.password=

pring.datasource.driver-class-name=org.postgresql.Driver